url: https://fairnessworkshop.com/
baseurl: /

# Site settings
title: 1s International Workshop on Software Fairness
email: spinolaro@vcu.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Ronnie de Souza Santos
  pic: 1
  position: Chair
  affiliation: University of Calgary
  social:
    - title: twitter
      url: https://x.com/softwaronnie
    - title: linkedin
      url: https://www.linkedin.com/in/drdesouzasantos/
    - title: envelope
      url: mailto:ronnie.desouzasantos@ucalgary.ca

- name: Rodrigo Spínola
  pic: 2
  position: Chair
  affiliation: Virginia Commonwealth University
  social:
    - title: twitter
      url: https://x.com/rodrigoospinola
    - title: linkedin
      url: https://www.linkedin.com/in/rodrigoospinola/
    - title: envelope
      url: mailto:spinolaro@vcu.edu

- name: Felipe Fronchetti
  pic: 3
  position: Social Chair
  affiliation: Louisiana State University
  social:
    - title: twitter
      url: https://x.com/fronchat
    - title: linkedin
      url: https://www.linkedin.com/in/fronchat/
    - title: envelope
      url: mailto:fronchettl@vcu.edu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/fairsoft
  - title: github
    url: http://github.com/fairsoft

# Build settings
markdown: kramdown
permalink: pretty